#!/bin/bash
# ============================================================
# SETUP & TESTING SCRIPT - Lab Session 12 SPA
# ============================================================
# Jalankan script ini untuk setup lengkap dan test API

echo "🚀 Lab 12 SPA Setup & Testing Script"
echo "===================================="

# 1. Pastikan Backend Running
echo ""
echo "📌 STEP 1: Setup Backend Django"
echo "--------"
echo "✓ Pastikan sudah di folder project: /Users/user/Documents/pi/project-2026-Dito1290"
echo "✓ Pastikan Python venv sudah activated: source venv/bin/activate"
echo ""
echo "Jalankan Backend Django:"
echo "  python manage.py runserver"
echo ""
echo "Verifikasi Backend running:"
echo "  curl -v http://127.0.0.1:8000/api/token/"
echo "  (Harusnya return 405 Method Not Allowed, bukan 404 atau refused connection)"

# 2. Frontend Setup
echo ""
echo "📌 STEP 2: Setup Frontend"
echo "--------"
echo "✓ Buka terminal baru"
echo "✓ Navigasi ke: /Users/user/Documents/pi/project-2026-Dito1290/smartcity_citizen_spa_24782073/"
echo ""
echo "Jalankan Live Server (port 5500):"
echo "  python -m http.server 5500"
echo ""
echo "Atau gunakan VS Code Live Server Extension:"
echo "  Klik kanan index.html → Open with Live Server"

# 3. Testing Workflow
echo ""
echo "📌 STEP 3: Testing Workflow"
echo "--------"
echo ""
echo "A. Login (Jalankan di Browser Console)"
echo "   1. Buka: http://127.0.0.1:5500"
echo "   2. Klik 'Masuk' → Login dengan akun yang sudah terdaftar"
echo "   3. Tunggu redirect ke Dashboard"
echo ""
echo "B. Verifikasi Token"
echo "   1. Buka DevTools (F12)"
echo "   2. Console tab"
echo "   3. Paste: localStorage.getItem('access_token')"
echo "   4. Lihat ada token atau tidak"
echo ""
echo "C. Cek API Response"
echo "   Di Console, paste:"
echo "   const token = localStorage.getItem('access_token');"
echo "   fetch('http://127.0.0.1:8000/api/report/?tab=my_reports', {"
echo "       headers: {'Authorization': \`Bearer \${token}\`}"
echo "   }).then(r => { console.log('Status:', r.status); return r.json(); })"
echo "    .then(data => console.log('Data:', data));"
echo ""
echo "D. Lihat Debug Log"
echo "   Console akan show: [API] GET /api/report/?tab=my_reports"
echo "   Cek ada 'Bearer token' atau tidak"
echo ""

# 4. Troubleshooting
echo ""
echo "📌 TROUBLESHOOTING"
echo "--------"
echo ""
echo "❌ Loading spinner stuck:"
echo "   → Buka DevTools Console (F12)"
echo "   → Lihat error merah apa"
echo "   → Pastikan Backend berjalan di port 8000"
echo ""
echo "❌ Error 401 Unauthorized:"
echo "   → Token invalid/expired"
echo "   → Login ulang"
echo "   → Paste di console: localStorage.clear(); location.reload();"
echo ""
echo "❌ Error 403 Forbidden:"
echo "   → Akses ditolak, permission issue"
echo "   → Cek di Django admin: apakah user adalah 'Citizen'?"
echo ""
echo "❌ CORS Error:"
echo "   → Cek settings.py: CORS_ALLOWED_ORIGINS"
echo "   → Pastikan 'http://127.0.0.1:5500' ada di list"
echo ""
echo "❌ 404 Not Found untuk /api/report/:"
echo "   → Endpoint tidak terdaftar"
echo "   → Jalankan: python manage.py runserver"
echo "   → Cek: main_app/api_urls.py ada router.register()"
echo ""

echo ""
echo "✅ SEMUA SETUP SUDAH SELESAI!"
echo "=============================="
echo ""
echo "Next Step:"
echo "1. Terminal 1: python manage.py runserver"
echo "2. Terminal 2: cd smartcity_citizen_spa_24782073 && python -m http.server 5500"
echo "3. Browser: http://127.0.0.1:5500"
echo "4. Login dan lihat apakah dashboard memuat data"
echo ""
