# Generated by Django 4.2.30 on 2026-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_24782073', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
